# fly.toml app configuration file generated for promethium-network-website-production on 2023-08-22T19:16:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "promethium-network-website-production"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
